[pytest]
markers =
    smoke: testes rápidos para verificar funcionalidades principais
    regression: testes de regressão
    api: testes de API
    database: testes relacionados ao banco de dados
    slow: testes demorados

    